spring:
  datasource:
    username: statistics
    password: statistics
    url: jdbc:postgresql://localhost:5432/statistics
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update